import json
import os
import re
import time
from typing import Any, Dict, List, Optional

import requests
from bs4 import BeautifulSoup


# ============================================================
# CONFIGURATION
# ============================================================

FOREX_FACTORY_CALENDAR_URL = (
    "https://www.forexfactory.com/calendar/"
)

PHASE1_INPUT_FILE = "phase_1_data.json"
OUTPUT_FILE = "phase_2_data.json"

CACHE_FILE = "forex_factory_calendar_cache.json"
CACHE_TTL = 300  # 5 minutes

REQUEST_TIMEOUT = 30


# ============================================================
# SESSION
# ============================================================

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/140.0.0.0 Safari/537.36"
    ),
    "Accept": (
        "text/html,application/xhtml+xml,"
        "application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}

session = requests.Session()
session.headers.update(HEADERS)


# ============================================================
# UTILITIES
# ============================================================

def clean_text(value: Optional[str]) -> Optional[str]:
    """Normalize whitespace."""

    if value is None:
        return None

    value = re.sub(r"\s+", " ", value).strip()

    return value if value else None


def is_cloudflare_block(response: requests.Response) -> bool:
    """Detect common Cloudflare/challenge responses."""

    if response.status_code in (403, 429, 503):
        return True

    text = response.text.lower()

    markers = [
        "cloudflare",
        "cf-chl-",
        "challenge-platform",
        "checking your browser",
        "just a moment",
        "verify you are human",
    ]

    return any(marker in text for marker in markers)


# ============================================================
# LOAD PHASE 1 DATA
# ============================================================

def load_phase1_data() -> List[Dict[str, Any]]:
    """Load events generated by phase_1.py."""

    if not os.path.exists(PHASE1_INPUT_FILE):
        raise FileNotFoundError(
            f"{PHASE1_INPUT_FILE} does not exist. "
            "Run phase_1.py first."
        )

    with open(
        PHASE1_INPUT_FILE,
        "r",
        encoding="utf-8",
    ) as file:
        data = json.load(file)

    if not isinstance(data, list):
        raise ValueError(
            "Phase 1 JSON must contain a list."
        )

    print(f"[PHASE 2] Loaded {len(data)} Phase 1 events")

    return data


# ============================================================
# FETCH CALENDAR HTML
# ============================================================

def load_cached_html() -> Optional[str]:
    """Load cached calendar HTML if still valid."""

    if not os.path.exists(CACHE_FILE):
        return None

    try:
        with open(
            CACHE_FILE,
            "r",
            encoding="utf-8",
        ) as file:
            cache = json.load(file)

        timestamp = cache.get("timestamp")
        html = cache.get("html")

        if not timestamp or not html:
            return None

        age = time.time() - timestamp

        if age > CACHE_TTL:
            print("[PHASE 2 / CACHE] Cache expired")
            return None

        print(
            "[PHASE 2 / CACHE] Using cached calendar HTML "
            f"({int(age)} seconds old)"
        )

        return html

    except Exception as exc:
        print(f"[PHASE 2 / CACHE] Failed to read cache: {exc}")
        return None


def save_html_cache(html: str) -> None:
    """Save calendar HTML to cache."""

    try:
        with open(
            CACHE_FILE,
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                {
                    "timestamp": time.time(),
                    "html": html,
                },
                file,
            )

    except Exception as exc:
        print(f"[PHASE 2 / CACHE] Failed to save cache: {exc}")


def fetch_calendar_html() -> Optional[str]:
    """Fetch the Forex Factory calendar HTML."""

    cached_html = load_cached_html()

    if cached_html:
        return cached_html

    print("\n[PHASE 2] Fetching Forex Factory calendar HTML...")

    try:
        response = session.get(
            FOREX_FACTORY_CALENDAR_URL,
            timeout=REQUEST_TIMEOUT,
        )

        print(f"[PHASE 2] HTTP status: {response.status_code}")

        if is_cloudflare_block(response):
            print(
                "[PHASE 2] Cloudflare/rate-limit response detected. "
                "HTML unavailable."
            )
            return None

        response.raise_for_status()

        html = response.text

        save_html_cache(html)

        return html

    except requests.RequestException as exc:
        print(f"[PHASE 2] Request failed: {exc}")
        return None


# ============================================================
# EXTRACT EVENT ID / URL
# ============================================================

def extract_event_id_and_url(
    event_element,
) -> tuple:
    """Extract event ID and event URL from the calendar event link."""

    if not event_element:
        return None, None

    link = event_element.find("a", href=True)

    if not link:
        link = event_element.select_one("a[href]")

    if not link:
        return None, None

    href = link.get("href")

    if not href:
        return None, None

    # Forex Factory event URLs are commonly:
    # /calendar?event=148447
    from urllib.parse import parse_qs, urljoin, urlparse

    full_url = urljoin(
        FOREX_FACTORY_CALENDAR_URL,
        href,
    )

    parsed = urlparse(full_url)
    query = parse_qs(parsed.query)

    event_ids = query.get("event")

    if not event_ids:
        return None, full_url

    return event_ids[0], full_url


# ============================================================
# PARSE CALENDAR HTML
# ============================================================

def parse_calendar_html(
    html: str,
) -> List[Dict[str, Any]]:
    """Parse calendar rows and extract event IDs/URLs."""

    print("\n[PHASE 2] Parsing calendar HTML...")

    soup = BeautifulSoup(html, "html.parser")

    rows = soup.select("tr.calendar__row")

    print(f"[PHASE 2] Found {len(rows)} calendar rows")

    events = []
    current_date = None

    for row in rows:

        # DATE
        date_element = row.select_one(
            ".calendar__date"
        )

        if date_element:
            current_date = clean_text(
                date_element.get_text(
                    " ",
                    strip=True,
                )
            )

        # TIME
        time_element = row.select_one(
            ".calendar__time"
        )

        event_time = (
            clean_text(
                time_element.get_text(
                    " ",
                    strip=True,
                )
            )
            if time_element
            else None
        )

        # CURRENCY
        currency_element = row.select_one(
            ".calendar__currency"
        )

        currency = (
            clean_text(
                currency_element.get_text(
                    " ",
                    strip=True,
                )
            )
            if currency_element
            else None
        )

        # IMPACT
        impact_element = row.select_one(
            ".calendar__impact"
        )

        impact = None

        if impact_element:
            impact_span = impact_element.select_one("span")

            if impact_span:
                class_text = " ".join(
                    impact_span.get("class", [])
                ).lower()

                if "high" in class_text:
                    impact = "High"
                elif "medium" in class_text:
                    impact = "Medium"
                elif "low" in class_text:
                    impact = "Low"
                elif "holiday" in class_text:
                    impact = "Holiday"

            if not impact:
                impact = clean_text(
                    impact_element.get_text(
                        " ",
                        strip=True,
                    )
                )

        # EVENT
        event_element = row.select_one(
            ".calendar__event"
        )

        event_name = (
            clean_text(
                event_element.get_text(
                    " ",
                    strip=True,
                )
            )
            if event_element
            else None
        )

        event_id, event_url = extract_event_id_and_url(
            event_element
        )

        # ACTUAL
        actual_element = row.select_one(
            ".calendar__actual"
        )

        actual = (
            clean_text(
                actual_element.get_text(
                    " ",
                    strip=True,
                )
            )
            if actual_element
            else None
        )

        # FORECAST
        forecast_element = row.select_one(
            ".calendar__forecast"
        )

        forecast = (
            clean_text(
                forecast_element.get_text(
                    " ",
                    strip=True,
                )
            )
            if forecast_element
            else None
        )

        # PREVIOUS
        previous_element = row.select_one(
            ".calendar__previous"
        )

        previous = (
            clean_text(
                previous_element.get_text(
                    " ",
                    strip=True,
                )
            )
            if previous_element
            else None
        )

        if not currency and not event_name:
            continue

        events.append({
            "date": current_date,
            "time": event_time,
            "currency": currency,
            "impact": impact,
            "event": event_name,
            "actual": actual,
            "forecast": forecast,
            "previous": previous,
            "event_id": event_id,
            "event_url": event_url,
        })

    print(f"[PHASE 2] Parsed {len(events)} calendar events")

    return events


# ============================================================
# SAVE PHASE 2 DATA
# ============================================================

def save_data(events: List[Dict[str, Any]]) -> None:
    """Save Phase 2 scraped HTML data."""

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            events,
            file,
            indent=4,
            ensure_ascii=False,
        )

    print(f"\n[PHASE 2] Saved {len(events)} events")
    print(f"[PHASE 2] Output: {OUTPUT_FILE}")


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    print("=" * 70)
    print("FOREX FACTORY SCRAPER - PHASE 2")
    print("=" * 70)

    # Phase 2 is intentionally independent from Phase 1 execution.
    # It reads phase_1_data.json only to know the expected
    # calendar events, then scrapes the HTML for additional data.

    phase1_events = load_phase1_data()

    html = fetch_calendar_html()

    if not html:
        raise RuntimeError(
            "Could not fetch Forex Factory calendar HTML."
        )

    html_events = parse_calendar_html(html)

    save_data(html_events)


if __name__ == "__main__":
    try:
        main()

    except KeyboardInterrupt:
        print("\nStopped by user.")

    except Exception as exc:
        print(f"\n[FATAL] {exc}")
